FROM node:22-alpine AS base

WORKDIR /app

ENV NODE_ENV=production

RUN apk add --no-cache openssl

COPY backend/package.json backend/tsconfig.json backend/prisma ./backend/
COPY backend/src ./backend/src

WORKDIR /app/backend

RUN npm install --omit=dev && npx prisma generate && npm run build

EXPOSE 4000

CMD ["node", "dist/index.js"]

